version: 2.1

jobs:
  run-bot:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r requirements.txt
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver
      - run:
          name: Run Bot
          command: |
            python main.py
      - store_artifacts:
          path: product_check.log

  watchdog:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Cancel Workflow After Timeout
          command: |
            echo "Waiting 10 minutes before cancelling workflow..."
            sleep 600

            echo "Cancelling workflow: $CIRCLE_WORKFLOW_ID"
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
              https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel \
              -H "Circle-Token: ${CIRCLECI_TOKEN}" \
              -H "Content-Type: application/json")

            echo "Cancel API response: $RESPONSE"

            if [ "$RESPONSE" -eq 202 ]; then
              echo "✅ Workflow cancelled successfully."
            else
              echo "❌ Workflow cancel failed with response code: $RESPONSE"
              exit 1
            fi

workflows:
  bot-workflow:
    jobs:
      - run-bot
      - watchdog
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only: main
