version: 2.1

jobs:
  run-bot:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r requirements.txt
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver
      - run:
          name: Run Bot
          command: |
            python main.py
      - store_artifacts:
          path: product_check.log

  watchdog:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Wait and Cancel Pipeline if Needed
          command: |
            echo "Waiting for 10 minutes..."
            sleep 600  # 600s = 10 mins
            echo "Canceling workflow now..."
            curl -X POST "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel" \
              -H "Circle-Token: ${CIRCLECI_TOKEN}" \
              -H "Content-Type: application/json"

workflows:
  bot-workflow:
    jobs:
      - run-bot
      - watchdog
    triggers:
      - schedule:
          cron: "0,15,30,45 * * * *"
          filters:
            branches:
              only: main
