name: Amul Protein Notifier

on:
  # Trigger the workflow on a schedule (e.g., every 5 minutes)
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  check-products:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Chrome and ChromeDriver (required for Selenium)
      - name: Install Chrome and ChromeDriver
        run: |
          # Install dependencies for snap
          sudo apt-get update
          sudo apt-get install -y snapd

          # Install Chromium using snap
          sudo snap install chromium

          # Install ChromeDriver by downloading it directly
          # First, find the version of Chromium installed
          CHROMIUM_VERSION=$(chromium --version | grep -oP 'Chromium \K\d+')
          echo "Chromium version: $CHROMIUM_VERSION"

          # Download the matching ChromeDriver version
          CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROMIUM_VERSION}"
          CHROMEDRIVER_VERSION=$(curl -sS $CHROMEDRIVER_URL)
          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"

          # Download and unzip ChromeDriver
          # Remove any existing chromedriver to avoid conflicts
          sudo rm -f /usr/bin/chromedriver
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/
          sudo chmod +x /usr/bin/chromedriver

          # Verify installations
          chromium --version
          chromedriver --version

      # Step 5: Run the script with environment variables
      - name: Run Amul Protein Notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PINCODE: ${{ secrets.PINCODE }}
          PRODUCT_NAMES: ${{ secrets.PRODUCT_NAMES }}
        run: python main.py

      # Step 6: Debug - List files
      - name: Debug - List files
        run: ls -la

      # Step 7: Upload logs
      - name: Upload logs
        if: always()  # Run even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: product-check-logs
          path: product_check.log