name: Amul Protein Notifier

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install chromium
          chromium --version
          CHROMEDRIVER_VERSION="137.0.7151.103"
          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip"
          sudo unzip /tmp/chromedriver.zip chromedriver-linux64/chromedriver -d /usr/bin/
          sudo mv /usr/bin/chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Run Amul Protein Notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python main.py

      - name: Debug - List files
        run: ls -la

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: product-check-logs
          path: product_check.log