name: Amul Protein Notifier

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq
          # Fetch the stable Chrome version from Chrome for Testing
          CHROME_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r ".channels.Stable.version")
          echo "Installing Chrome version: $CHROME_VERSION"
          # Download and install Chrome (not Chromium) to match ChromeDriver
          wget -O /tmp/chrome.zip "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-linux64.zip"
          unzip /tmp/chrome.zip -d /tmp/chrome
          sudo mv /tmp/chrome/chrome-linux64/chrome /usr/bin/chrome
          sudo chmod +x /usr/bin/chrome
          chrome --version
          # Download the matching ChromeDriver
          echo "Downloading ChromeDriver version: $CHROME_VERSION"
          wget -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          sudo unzip /tmp/chromedriver.zip chromedriver-linux64/chromedriver -d /usr/bin/
          sudo mv /usr/bin/chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Kill lingering Chrome processes
        run: |
          echo "Killing any lingering Chrome/Chromium processes..."
          pkill -9 chrome || true
          pkill -9 chromium || true
          echo "Lingering processes killed."

      - name: Clean up stale Chrome user data directories
        run: |
          echo "Cleaning up stale Chrome user data directories in /tmp..."
          rm -rf /tmp/.org.chromium.Chromium.*
          echo "Cleanup complete."

      - name: Run Amul Protein Notifier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python main.py

      - name: Debug - List files
        run: ls -la

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: product-check-logs
          path: product_check.log